package:
    name:           hidev-config
    namespace:      ahnames\hidev\config
    label:          AHnamesHiDevConfig
    title:          AHnames general hidev config
    type:           yii2-extension
    keywords:       ahnames, hidev, config
    year:           2015

require:
    ahnames/hidev-config:       "*@dev"
    ahnames/hidev-config-php:   "*@dev"
