vendor:
    name:       ahnames
    title:      AHnames
    github:     https://github.com/ahnames
    homepage:   https://ahnames.com/
    email:      support@ahnames.com
    license:    ''
    authors:
        hiqsol:
            name:       Andrii Vasyliev
            email:      sol@hiqdev.com
            github:     https://github.com/hiqsol
            homepage:   https://hipanel.com/
